video_extensions:
- .mp4
- .avi
- .mov
- .mkv
- .webm
- .flv
- .wmv
duration_method: jenks
quality_method: jenks
duration_short_max: 60
duration_medium_max: 300
quality_high_min: 1.0
quality_medium_min: 0.5
bitrate_factor: 0.13
num_categories: 3
